# Prereq: Ensure to set resources cpu limits and HPA object is in same namespace as deployment
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: aks-helloworld-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acs-helloworld-aks-helloworld
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: aks-helloworld-two-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acs-helloworld-aks-helloworld-two
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50